//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingsman20.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public Nullable<int> ID { get; set; }
        public string Ttile { get; set; }
        public string Adress { get; set; }
        public string Email { get; set; }
        public int ProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
